import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  pokemonSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate sidebar from all files in ../docs
    },
  ],
};

export default sidebars;
