import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'autogenerated', 
      dirName: '.', // Generates sidebar from all docs in ../docs
    },
  ],
};

export default sidebars;